### ISSUE TITLE
Git no longer has access to keys added via ssh-agent as of 1.0.3

### ISSUE THREAD

**Issue by gotgenes** [dyuri/xontrib-ssh-agent#1]
Since the release of xontrib-ssh-agent 1.0.3, Git no longer has access to the SSH keys added via `ssh-add`. When invoking any `git` command, even `git status` in xonsh, something (git?) is attempting to load the key again.

```
$ ssh-add -l                                                                                                            
2048 SHA256:ZKbZN[…] chris.lasher@[…] (RSA)
$ git status                                                                                                            
Loading keys:
    /Users/chris.lasher/.ssh/id_rsa
Enter passphrase for /Users/chris.lasher/.ssh/id_rsa: 
```

I can resolve this issue with

```
xpip uninstall xontrib-ssh-agent
xpip install xontrib-ssh-agent==1.0.2
```

**Comment by dyuri** [comment]
Thanks for reporting this, in 1.0.3 I switched to use `repassh` to support multiple agents, but I seem to forgot about the default one.

**Comment by dyuri** [comment]
I've added the `USE_RUNNING_AGENT` option to `repassh` (enabled by default), and updated the requirements here to use that version at least. 
Released as [1.0.5](https://pypi.org/project/xontrib-ssh-agent/1.0.5/)

**Comment by dyuri** [comment]
@gotgenes could you confirm that the latest version fixes your issue?

**Comment by gotgenes** [comment]
@dyuri thanks for your quick response!

After upgrading to the newest versions of xontrib-ssh-agent and repassh, I still see this behavior where the xontrib will prompt me for my default key's password, even though I added the default key in a prior `ssh-add`:

```
$ ssh-add -l                                                                                                            
The agent has no identities.
$ ssh-add                                                                                                               
Enter passphrase for /Users/chris/.ssh/id_rsa: 
Identity added: /Users/chris/.ssh/id_rsa (/Users/chris/.ssh/id_rsa)
$ git status                                                                                                            
Loading keys:
    /Users/chris/.ssh/id_rsa
Enter passphrase for /Users/chris/.ssh/id_rsa: 
```

I note that I'm even prompted for Git commands that require no SSH access (I'm pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> to cancel the password entry):

```
$ git version                                                                                                           
Loading keys:
    /Users/chris/.ssh/id_rsa
Enter passphrase for /Users/chris/.ssh/id_rsa: 
git version 2.26.0
```

Here's some more info on my system
```
$ xonfig info                                                                                                           
+------------------+-----------------+
| xonsh            | 0.9.15          |
| Python           | 3.8.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.4           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
$ xpip list                                                                                                             
Package           Version
----------------- -------
pip               20.0.2 
prompt-toolkit    3.0.4  
Pygments          2.6.1  
repassh           1.0.2  
setproctitle      1.1.10 
setuptools        46.1.1 
six               1.14.0 
wcwidth           0.1.9  
wheel             0.34.2 
xonsh             0.9.15 
xontrib-autojump  1.2    
xontrib-kitty     0.0.2  
xontrib-pyenv     1.0.3  
xontrib-ssh-agent 1.0.5  
```

**Comment by dyuri** [comment]
Could you please try to create a `config.json` for `repassh` (more info: https://github.com/dyuri/repassh/#config-file-with-multiple-identities) and set *VERBOSITY* to 4?

Something like:
```
{
  "VERBOSITY": 4
}
```

If I set the `ssh-agent` related variables manually:
```
$ git pull                                                                                            
`repassh` was invoked by ``, not using `sys.exit`.
Will run 'git' as ssh binary - set by user via BINARY_SSH
Env. agent is running
All keys already loaded
+ exec git pull
...
```

Without setting the environment variables:
```
$ git pull                                                                                            
`repassh` was invoked by ``, not using `sys.exit`.
Will run 'git' as ssh binary - set by user via BINARY_SSH
Agent for identity dyuri ready
All keys already loaded
+ . /home/dyuri/.ssh/agents/agent-dyuri-dyuri
+ exec git pull
...
```

When the env. variables are set, but the agent is not running:
```
$ git pull                                                                                            
`repassh` was invoked by ``, not using `sys.exit`.
Will run 'git' as ssh binary - set by user via BINARY_SSH
Agent default not running
Agent for identity dyuri ready
All keys already loaded
+ . /home/dyuri/.ssh/agents/agent-dyuri-dyuri
+ exec git pull
```

**Comment by gotgenes** [comment]
Sure thing. Here's what I see when I set `"VERBOSITY": 4`:

```
$ git status                                                                                                            
`repassh` was invoked by ``, not using `sys.exit`.
Will run 'git' as ssh binary - set by user via BINARY_SSH
Agent for identity chris ready
Loading keys:
    /Users/chris/.ssh/id_rsa
Enter passphrase for /Users/chris/.ssh/id_rsa: 
```

It looks similar to the second snippet above except it does not have "All keys already loaded" and it does not have a path to an agent.

Here are the steps to reproduce:

1. Restart the computer and open xonsh with xontrib-ssh-agent==1.0.5 installed.
1. Run `ssh-add` with no arguments to load the default private key `~/.ssh/id_rsa`
1. Enter the password for `~/.ssh/id_rsa`
1. `cd` into a directory that's part of a Git repository
1. Run any `git` command, like `git status`.

**Comment by dyuri** [comment]
Thanks!

Hmm, do you have `ssh-agent` running and it's environment variables included somewhere?
If I execute `ssh-add` without `ssh-agent` then it fails with
```
Could not open a connection to your authentication agent.
```
(I'm using linux, but macOS might provide some `ssh-agent` like service by default.)

But anyway, I'm gonna switch the availability of `ssh-agent` by executing `ssh-add -l` - without checking the environment variables.

**Comment by dyuri** [comment]
Updated `repassh` and the dependency here, @gotgenes please check if you have time.

**Comment by gotgenes** [comment]
Following the same steps, now with the updated versions of repassh (1.0.3) and xontrib-ssh-agent (1.0.6), I can happily report that this issue appears resolved:

```
$ git fetch                                                                                                             
`repassh` was invoked by ``, not using `sys.exit`.
Will run 'git' as ssh binary - set by user via BINARY_SSH
Global agent is running
All keys already loaded
+ exec git fetch
```

>(I'm using linux, but macOS might provide some ssh-agent like service by default.)

Yes, this appears to be the case with macOS. There seems to always be an ssh-agent running upon boot.

Thanks for looking into this, @dyuri!
