### ISSUE TITLE
Output from git cannot be redirected

### ISSUE THREAD

**Issue by gotgenes** [dyuri/xontrib-ssh-agent#2]
Output from `git` can no longer be redirected after loading xontrib-ssh-agent. It appears to have to do with aliasing `git` to a Python function.

```
$ git branch | grep master                                                                              
* master
  release_5.15.1
$ git_func = aliases['git']                                                                                             
$ del aliases['git']                                                                                                    
$ git branch --merged master | grep master                                                                              
* master
$ aliases['git'] = git_func                                                                                             
$ git branch | grep master                                                                              
* master
  release_5.15.1
```

**Comment by dyuri** [comment]
Hmm, according to the [xonsh documentation](https://xon.sh/tutorial.html#callable-aliases) this should work if I add `stdin` and `stdout` parameters to the function, but it isn't working for me atm.

**Comment by dyuri** [comment]
Do you have the `bashisms` xontrib loaded? It seems to break the alias function piping.
When I removed it from my config I was able to grep git's output.

**Comment by gotgenes** [comment]
Hmm, no, I have the following xontribs loaded:

```
xontrib load autojump jedi kitty pyenv ssh_agent vox
```

**Comment by dyuri** [comment]
Ok, this seems to be a different issue, when bashisms is loaded for me then piping an alias function to a command stuck, and I need to kill the shell to finish it.
Piping now does not work indeed, but the shell at least is not stuck :)

**Comment by gotgenes** [comment]
Correct, the shell definitely still functions, it's just that the stdout/stderr are not getting redirected.

**Comment by dyuri** [comment]
I have a working pipeable version, but highlighting is lost, I still want to give it a try tomorrow.

**Comment by dyuri** [comment]
I have a working pipeable version, but highlighting is lost, I still want to give it a try tomorrow.

**Comment by dyuri** [comment]
Version 1.0.8 (and `repassh` 1.0.4) released, for me the `git` alias' output can be piped and isn't striped from the colors.
Could you please check that `git` commands that execute an editor works as well? (`git ci` without `-m` for example) My `vim` was stuck with the previous change.

**Comment by gotgenes** [comment]
I can confirm piping now works.

```
$ git branch | grep master                                                                                              
  master
```

Redirection of output fails, though.

```
$ git status > status                                                                                                   
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/base_shell.py", line 362, in default
    run_compiled_code(code, self.ctx, None, "single")
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/built_ins.py", line 1015, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/built_ins.py", line 981, in run_subproc
    command.end()
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/proc.py", line 2150, in end
    self._end(tee_output=tee_output)
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/proc.py", line 2158, in _end
    for _ in self.tee_stdout():
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/proc.py", line 2071, in tee_stdout
    for line in self.iterraw():
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/proc.py", line 2007, in iterraw
    stderr_lines = safe_readlines(stderr, 1024)
  File "/usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages/xonsh/proc.py", line 1796, in safe_readlines
    lines = handle.readlines(hint)
AttributeError: 'NoneType' object has no attribute 'readlines'
```

Then the very next command executed will actually cause xonsh to crash.

**Comment by dyuri** [comment]
Great.
It seems I can only choose two from the three features I want - piping, redirection and direct terminal output (for interactive commands / highlighting).

I uploaded a new version that replaces the `git` alias with `$GIT_SSH` environment variable. To use this you need to make sure that the `repassh` binary is somewhere in the `$PATH`.

**Comment by gotgenes** [comment]
>It seems I can only choose two from the three features I want - piping, redirection and direct terminal output (for interactive commands / highlighting).

Hmm, is there a change that can be requested upstream in xonsh that would help?

**Comment by gotgenes** [comment]
>To use this you need to make sure that the repassh binary is somewhere in the `$PATH`.

Because `repassh` is a dependency of `xontrib-ssh-agent`, is this path calculable, for a reasonable default?

**Comment by dyuri** [comment]
I'll try to debug the alias issues in `xonsh`, I only want to open an issue when I know some details.

`repassh` is installed for sure, but its install path depends on how you installed it, atm I don't know how could we calculate it - that's why I used the aliases, they are always there.
For example if I use `pip install --user repassh`, it installs the binary into `~/.local/bin`, but without the `--user` option, it is insalled under `/usr` (but in the latter case it should be already on the `$PATH`).

If it's installed by `xpip` or the same way you installed `xonsh`, I think it should work by default, doesn't it?

**Comment by gotgenes** [comment]
On xonsh 0.9.15 on MacOS, the directory where `repassh` installs from `xpip install` does not appear to be on `$PATH` by default.

```
$ which repassh                                                                                                         
repassh not in $PATH or xonsh.builtins.aliases
$ xpip show repassh                                                                                                     
Name: repassh
Version: 1.0.4
Summary: SSH wrapper to load private keys on first execution
Home-page: https://github.com/dyuri/repassh
Author: Gyuri Horak
Author-email: dyuri@horak.hu
License: MIT
Location: /usr/local/Cellar/xonsh/0.9.15/libexec/lib/python3.8/site-packages
Requires: 
Required-by: xontrib-ssh-agent
$ ls /usr/local/Cellar/xonsh/0.9.15/libexec/bin/                                                                        
activate         activate_this.py pip              pygmentize       python3          wheel            xonsh-cat
activate.csh     easy_install     pip3             python           python3.8        xon.sh
activate.fish    easy_install-3.8 pip3.8           python-config    repassh          xonsh
```

My best guess is that's a "good thing". I don't actually want the `python` executable in `/usr/local/Cellar/xonsh/0.9.15/libexec/bin/` overriding my OS default `python` (which is actually managed by pyenv).

This actually made me wonder how `xpip` works, because it's not in the bin directory, and it turns out it's a xonsh alias:

```
$ aliases['xpip']                                                                                                       
['/usr/local/Cellar/xonsh/0.9.15/libexec/bin/python3.8', '-m', 'pip']
```

I went to see how this alias is defined, and it uses [a function in `xonsh/.aliases.py` called `detect_xpip_alias()`](https://github.com/xonsh/xonsh/blob/b37675a6e8fd6d1bebd2a89ebfb1b3069c38202b/xonsh/aliases.py#L734-L756), which essentially relies on `sys.executable`. xontrib-ssh-agent could try doing something like this.

That said, I'm not having success when manually setting an alias for repassh:

```
$ aliases['repassh'] = "/usr/local/Cellar/xonsh/0.9.15/libexec/bin/repassh"                                             
$ git fetch                                                                                                             
error: cannot run repassh: No such file or directory
error: cannot run repassh: No such file or directory
fatal: unable to fork
$ which repassh                                                                                                         
/usr/local/Cellar/xonsh/0.9.15/libexec/bin/repassh
```

I'm not sure why this is; my best guess is that the git commands are executing through subprocess without shell support, so they can't leverage xonsh aliases. I would expect to see similar behavior if `xpip` were the target "executable", too.

**Comment by dyuri** [comment]
In this case the easiest way for you to set $GIT_SSH to `/usr/local/Cellar/xonsh/0.9.15/libexec/bin/repassh` manually.
I have updated the documentation about it, and added support for defining the `repassh` binary via `$REPASSH_COMMAND` (this should be set before loading the xontrib).

**Comment by gotgenes** [comment]
I have added the following lines to the beginning of my `.xonshrc`:

```
import os.path
import sys

$REPASSH_COMMAND = os.path.join(os.path.dirname(sys.executable), 'repassh')

del os
del sys
```

This seems to work. Thanks!

I am also wondering if this part of the code:

```
if repassh_command:
    $GIT_SSH = repassh_command
```

should be changed to

```
if not 'GIT_SSH' in ${...} and repassh_command:
    $GIT_SSH = repassh_command
```

in case the user has already set `$GIT_SSH`.

**Comment by dyuri** [comment]
Sure, changed.

**Comment by gotgenes** [comment]
One new behavior I've noticed is that repassh outputs lines about checking for an agent and available keys, twice, now:

```
$ git fetch                                                                                                             
Global agent is running
All keys already loaded
Global agent is running
All keys already loaded
```

Prior versions only output these lines once, each.

**Comment by dyuri** [comment]
Yep, git calls the $GIT_SSH command twice, which is now `repassh` checking the keys and calling `ssh`. Prior versions that used the alias for git called `repassh` once which checked the keys. then called `git` (which executed `ssh` twice).

If you set your `VERBOSITY` back to 2 or less (in `repassh` config), you won't see those messages.

**Comment by gotgenes** [comment]
Thanks, @dyuri!
